spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lyh.1997
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=UTF-8&useSSL=false

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
  #    show-sql: true



  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  thymeleaf:
    #  关闭视图模板缓存
    cache: false

  http:
    encoding:
      force: true
      charset: UTF-8
  servlet:
    multipart:
      enabled: true
      location: G:/tmp/file
      file-size-threshold: 10MB
      max-file-size: 20MB
  redis:
    host: localhost
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    # database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0


user:
  key: USER
#debug: true
logging:
  config: classpath:logback-spring.xml

qiniu:
  ## 此处填写你自己的七牛云 access key
  accessKey: RRwt79cxbDBkVBPo92ZnIlNiynBCLBDM5RPQ3MHr
  ## 此处填写你自己的七牛云 secret key
  secretKey: nKFMamwaBO3ev87_i68DQwHnMnIWUm7qQKtj8VNs
  ## 此处填写你自己的七牛云 bucket
  bucket: xfdwjd1997leon
  ## 此处填写你自己的七牛云 域名
  prefix: raxes0mqf.bkt.clouddn.com
ceph:
  accessKey: HXYN0M01L86QP3NJLSCK
  secretKey: EUR3LE0HpV7vCwTMORawH5HNpPCJ2dnBwfIy2SiJ
  bucket: my-first-s3-bucket
  ## 填写域名或者IP
  host: 192.168.1.112:80

jwt:
  #token返回头部
  header: "Authorization"
  #密钥
  secret: "sztu@60219970803"
  #token有效时间 (小时) 建议一小时以上
  expireTime: 1
debug: true
server:
  port: 8081
  servlet:
    context-path: /cloud
